#!/bin/bash
# TODO: Find a less trashy way to get the next available error code

shopt -s globstar

for i in 1 2
do
  last=$(grep -hv "^prop" ./**/*.hs | grep -Ewo "$i[0-9]{3}" | sort -n | tail -n 1)
  echo "Next ${i}xxx: $((last+1))"
done
